# Generated by Django 4.1 on 2022-09-08 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=264)),
                ('location', models.CharField(max_length=264)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='taskDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=264)),
                ('status', models.CharField(max_length=25)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todoapp.userdetail')),
            ],
        ),
    ]
